#!/bin/bash

function usage () {
    echo "Usage: $0 <copy/paste/tee>"
    echo ""
    echo "tee will both copy to clipboard and print the result"
    exit 1
}

function noclip () {
    echo "No clipboard function found"
    echo "On linux, try installing xclip."
    exit 2
}

function fix_tmux_on_linux () {
    # This is a hack that happens to fix copy/paste on the linux machines I use
    if [ -n "$TMUX" ] && [ -z "$DISPLAY" ]; then
        export DISPLAY=:0
    fi
}

function copy () {
    if type pbcopy &> /dev/null; then
        pbcopy <&0
    elif type xclip &> /dev/null; then
        fix_tmux_on_linux
        xclip -sel clip -i <&0
    else
        noclip
    fi
}

function paste () {
    if type pbpaste &> /dev/null; then
        pbpaste
    elif type xclip &> /dev/null; then
        fix_tmux_on_linux
        xclip -sel clip -o
    else
        noclip
    fi
}


if [ "$1" == "copy" ]; then
    copy
elif [ "$1" == "paste" ]; then
    paste
elif [ "$1" == "tee" ]; then
    copy
    paste
else
    usage
fi
