#!/bin/bash

function usage () {
    echo "Usage: $0 <copy/paste>"
    exit 1
}

function noclip () {
    echo "No clipboard function found"
    echo "On linux, try installing xclip."
    exit 2
}

function copy () {
    if type pbcopy &> /dev/null; then
        pbcopy <&0
    elif type xclip &> /dev/null; then
        xclip -sel clip -i <&0
    else
        noclip
    fi
}

function paste () {
    if type pbpaste &> /dev/null; then
        pbpaste
    elif type xclip &> /dev/null; then
        xclip -sel clip -o <&0
    else
        noclip
    fi
}


if [ "$1" == "copy" ]; then
    copy
elif [ "$1" == "paste" ]; then
    paste
else
    usage
fi
