#!/bin/bash


# Set formatting macros
bold=`tput bold`
normal=`tput sgr0`

# Given a directory name (./dirname/), fetch remote changes
function fetchRepoUpdates () {
    dir="$1"
    pushd "$dir" > /dev/null
    printf "$(echo "$dir" | sed "s/\.\/\(.*\)\//\1/") "
    git fetch &> /dev/null
    popd > /dev/null
}

# Given a directory name (./dirname/), print out a status line for that git repo
function checkRepoStatus () {
    dir="$1"
    pushd "$dir" > /dev/null

    gitdir=$(echo "$dir" | sed "s/\.\/\(.*\)\//\1/")
    gitbranch=$(git rev-parse --abbrev-ref HEAD)
    gitstat=$(git status)

    uptodate=$(echo "$gitstat" | egrep "up-to-date" -o)
    ahead=$(echo "$gitstat" | egrep "ahead of '.+' by [0-9]+ commits?" -o | \
        sed "s/of '.\+' //")
    behind=$(echo "$gitstat" | egrep "behind '.+' by [0-9]+ commits?" -o | \
        sed "s/'.\+' //")
    diverged=$(echo "$gitstat" | egrep "[0-9]+ and [0-9]+ different commits?" -o | \
        sed "s/\([0-9]\+\) and \([0-9]\+\) different commits\?/\1 ahead, \2 behind/")
    unstaged=$(echo "$gitstat" | \
        egrep "(not staged for commit)|(Changed but not updated)" -o)
    staged=$(echo "$gitstat" | egrep "to be committed" -o)

    echo -en "${bold}$gitdir${normal}\t"

    if [ "$gitbranch" != "master" ]; then
        echo -en "\x1B[34m"
        echo -n "in branch $gitbranch"
    elif [ -n "$ahead" ]; then
        echo -en "\x1B[35m"
        echo -n "$ahead"
    elif [ -n "$behind" ]; then
        echo -en "\x1B[36m"
        echo -n "$behind"
    elif [ -n "$diverged" ]; then
        echo -en "\x1B[31m"
        echo -n "diverged ($diverged)"
    elif [ -n "$uptodate" ]; then
        if [ -n "$staged" ] || [ -n "$unstaged" ]; then
            echo -en "\x1B[33m"
        else
            echo -en "\x1B[32m"
        fi
        echo -n "up to date"
    else
        echo -n "no upstream"
    fi

    if [ -n "$staged" ] && [ -n "$unstaged" ]; then
        echo -en ", \x1B[33m"
        echo -n "staged and unstaged changes"
    elif [ -n "$staged" ]; then
        echo -en ", \x1B[33m"
        echo -n "staged changes"
    elif [ -n "$unstaged" ]; then
        echo -en ", \x1B[33m"
        echo -n "unstaged changes"
    fi

    echo -e "\x1B[0m"
    popd > /dev/null
}


# Parse flags
if [[ $@ =~ "-h" ]] || [[ $@ =~ "--help" ]]; then
    echo "Usage: $0 [-n/--nofetch] [directoryname (default cwd)]"
    echo ""
    echo "Searches the provided directory for git repositories, and shows the update"
    echo "status of those directories."
    echo ""
    echo "Unless --nofetch is specified, first fetches all remote changes for the"
    echo "searched repositories."
    exit 0
fi

fetch=true
if [ "$1" == "-n" ] || [ "$1" == "--nofetch" ]; then
    fetch=false
    shift 1
fi

if [ -n "$1" ]; then
    pushd "$1" > /dev/null
fi


# Check for updates
if [ $fetch == true ]; then
    echo "Checking for remote updates..."
    for dir in ./*/
    do
        if [ -d "$dir/.git" ]
        then
            fetchRepoUpdates "$dir"
        fi
    done
    printf "\n\n"
fi


# Print statuses, piping to columns for formatting
for dir in ./*/
do
    if [ -d "$dir/.git" ]
    then
        checkRepoStatus "$dir"
    fi
done | column -s $'\t' -t
