#!/bin/bash

function usage () {
    echo "Usage: $0 <command> [<arg> <arg>...]"
    exit 1
}

function nonotification () {
    echo "No notification function found..."
    exit 2
}


if [ -z "$1" ]; then
    usage
elif type osascript &> /dev/null; then
    eval $@
    osascript -e "display notification \" >> $*\" with title \"Command complete\""
elif type notify-send &> /dev/null; then
    eval $@
    notify-send --icon terminal "Command complete:" " >> $*"
else
    nonotification
fi
